resources/public/css/styles.css
resources/public/index.html
src/cljs/webchange/views.cljs

Re-make up select course view

---

package-lock.json
src/cljs/webchange/dashboard/classes/class_profile/views.cljs
src/cljs/webchange/dashboard/classes/classes_list/views.cljs
src/cljs/webchange/dashboard/classes/classes_menu/views.cljs
src/cljs/webchange/dashboard/events.cljs
src/cljs/webchange/dashboard/students/events.cljs
src/cljs/webchange/dashboard/students/students_list/views.cljs
src/cljs/webchange/dashboard/students/students_menu/views.cljs
src/cljs/webchange/routes.cljs

* move dispatch loading to routes.cljs

Refactor classes and students loading

---

npm-shrinkwrap.json
project.clj
src/clj/webchange/dataset/loader.clj
src/clj/webchange/server.clj
wiki/run.md

* made dataset dir configurable (defaults to resources/datasets/)
* added commands for uberjar file
* changed wiki.

Add dataset commands for uberjar file

---

src/cljs/webchange/dashboard/students/student_modal/views.cljs

- remove default DOB value
- disable form prefill
- add "required" asterisk.

Disable student modal pre-fill

---

src/cljs/webchange/dashboard/classes/class_modal/views.cljs
src/cljs/webchange/dashboard/classes/classes_list/views.cljs
src/cljs/webchange/dashboard/classes/events.cljs
src/cljs/webchange/dashboard/classes/subs.cljs
src/cljs/webchange/dashboard/classes/views.cljs
src/cljs/webchange/dashboard/events.cljs
src/cljs/webchange/dashboard/students/events.cljs
src/cljs/webchange/dashboard/students/student_modal/views.cljs
src/cljs/webchange/dashboard/students/students_list/views.cljs
src/cljs/webchange/dashboard/students/subs.cljs
src/cljs/webchange/dashboard/students/views.cljs
src/cljs/webchange/dashboard/views.cljs

- add confirm delete class modal
- disable delete non-empty class

Confirm delete class action

---

npm-shrinkwrap.json
resources/sql/class.sql
src/clj/webchange/class/core.clj
src/clj/webchange/class/handler.clj
src/cljs/webchange/dashboard/classes/classes_menu/views.cljs
src/cljs/webchange/dashboard/events.cljs
src/cljs/webchange/dashboard/students/events.cljs
src/cljs/webchange/dashboard/students/students_menu/views.cljs
src/cljs/webchange/dashboard/students/subs.cljs
test/clj/webchange/test/class/handler.clj
test/clj/webchange/test/fixtures/core.clj

- delete student will remove class and move a student to "Unassigned students"
- add unassigned students to the side menu
- fix validation for edit student (event data position)

Allow to unassign student, show unassigned students

---

src/cljs/webchange/dashboard/classes/class_modal/views.cljs
src/cljs/webchange/dashboard/classes/class_profile/views.cljs
src/cljs/webchange/dashboard/common/views_content_wrappers.cljs
src/cljs/webchange/dashboard/events.cljs
src/cljs/webchange/dashboard/students/events.cljs
src/cljs/webchange/dashboard/students/student_profile/views.cljs
src/cljs/webchange/dashboard/students/students_list/views.cljs
src/cljs/webchange/dashboard/students/subs.cljs

Navigation-connections added:
- Class profile -> Class edit
- Class profile -> Class delete
- Class profile -> Students list
- Student profile -> Student edit
- Student profile -> Student delete
- Student profile -> Class profile
- Students list -> Class profile

Navigation improvement

---

resources/datasets/test-concepts.edn
src/clj/webchange/demo_scenes/cinema/cinema.clj
src/clj/webchange/demo_scenes/cinema/cinema_video.clj
src/clj/webchange/demo_scenes/park/park_poem.clj
src/clj/webchange/scene.clj
wiki/installation.md

- fix concepts
- fix cinema and sandbox activities
- fix workflow actions

Fix concepts and activities 1-4 level 2

---

resources/sql/class.sql
resources/sql/progress.sql
src/clj/webchange/class/core.clj

- unassign course-stats when a student removed from a class.
- change course-stats class when students class updated.

Keep student list and class profile consistent

---

src/cljs/webchange/db.cljs
src/cljs/webchange/events.cljs
src/cljs/webchange/interpreter/components.cljs
src/cljs/webchange/interpreter/events.cljs
src/cljs/webchange/interpreter/executor.cljs
src/cljs/webchange/subs.cljs

- move sound settings under :settings key in app-db 
- save settings to progress on close settings 
- make settings a modal over the scene so that it does not interfere with scene actions.

Save settings

---

resources/courses/english/scenes/see_saw.edn
resources/courses/english/scenes/swings.edn
resources/datasets/english-concepts.edn
src/cljs/webchange/interpreter/events.cljs

- add level 1 activities 2-3
- fix default audio level

add english l1 a2-a3

---

resources/courses/english/course.edn
resources/courses/english/scenes/map.edn
resources/courses/english/scenes/park.edn
src/cljs/webchange/common/core.cljs
src/cljs/webchange/interpreter/components.cljs
src/cljs/webchange/interpreter/core.cljs
src/cljs/webchange/interpreter/events.cljs

- allow image filter transitions
- add brightness filters to location entrances
- allow transition deletion 
- add default hardcoded triggers

Change navigation helper

---

resources/courses/english/scenes/home.edn
resources/courses/english/scenes/map.edn
resources/courses/english/scenes/see_saw.edn
resources/courses/english/scenes/swings.edn
resources/datasets/english-concepts.edn
src/cljs/webchange/common/core.cljs
src/cljs/webchange/common/events.cljs
src/cljs/webchange/interpreter/core.cljs
src/cljs/webchange/interpreter/events.cljs
src/cljs/webchange/interpreter/variables/events.cljs
src/cljs/webchange/routes.cljs

- cleanup English scenes
- disable navigation helper during activity

Cleanup english demo

---

npm-shrinkwrap.json
resources/courses/test/course.edn
resources/courses/test/scenes/cinema.edn
resources/courses/test/scenes/cinema_video.edn
resources/courses/test/scenes/cycling_letters.edn
resources/courses/test/scenes/letter_intro.edn
resources/courses/test/scenes/magic_hat.edn
resources/courses/test/scenes/park_poem.edn
resources/courses/test/scenes/pinata.edn
resources/courses/test/scenes/running.edn
resources/courses/test/scenes/slide.edn
resources/courses/test/scenes/volleyball_letters.edn
resources/courses/test/scenes/writing_lesson.edn
resources/courses/test/scenes/writing_practice.edn
resources/datasets/test-concepts.edn
src/cljs/webchange/interpreter/events.cljs

Feature level 2 concepts

---

bin/run
resources/courses/test/scenes/home.edn
src/clj/webchange/assets/handler.clj
src/clj/webchange/common/audio_parser/recognizer.clj
src/clj/webchange/handler.clj
src/clj/webchange/scene.clj
src/cljs/webchange/editor/common/actions/action_form.cljs
src/cljs/webchange/editor/common/actions/action_forms/animation_sequence.cljs
src/cljs/webchange/editor/common/actions/events.cljs
src/cljs/webchange/editor/components/main_content_navigation/index.cljs
src/cljs/webchange/editor/events.cljs
test/cljs/webchange/editor/common/action_form/animation_sequence_panel_snapshots.cljs
wiki/run.md

* add upload dir environment variable
* moved "convert to animations" to animation sequence panel. and renamed it to LipSync

Fix uploading and detecting voiceovers

---

npm-shrinkwrap.json
resources/courses/test/course.edn
resources/courses/test/scenes/letter_intro.edn
resources/courses/test/scenes/magic_hat.edn
resources/courses/test/scenes/park_poem.edn
resources/courses/test/scenes/slide.edn
resources/courses/test/scenes/volleyball_letters.edn
resources/datasets/test-concepts.edn
src/cljs/webchange/common/core.cljs
src/cljs/webchange/editor/common/actions/action_form.cljs
src/cljs/webchange/editor/form_elements.cljs
src/cljs/webchange/editor/form_elements/wavesurfer.cljs

- save last audio waveform location

Feature lvl2 finish

---

resources/courses/test/scenes/book.edn
resources/courses/test/scenes/cycling.edn
resources/courses/test/scenes/cycling_letters.edn
resources/courses/test/scenes/hide_n_seek.edn
resources/courses/test/scenes/home.edn
resources/courses/test/scenes/letter_intro.edn
resources/courses/test/scenes/library.edn
resources/courses/test/scenes/running.edn
resources/courses/test/scenes/sandbox.edn
resources/courses/test/scenes/see_saw.edn
resources/courses/test/scenes/swings.edn
resources/courses/test/scenes/volleyball.edn
resources/courses/test/scenes/volleyball_letters.edn
resources/courses/test/templates/coaching.edn
resources/datasets/test-concepts.edn
src/clj/webchange/scene.clj
src/cljs/webchange/editor/common/actions/action_form.cljs
src/cljs/webchange/editor/common/actions/action_types.cljs
src/cljs/webchange/editor/components/data_sets/data_set_item/dataset_item_field.cljs
src/cljs/webchange/editor/form_elements/wavesurfer/wave_core.cljs
src/cljs/webchange/editor/form_elements/wavesurfer/wave_form.cljs
src/cljs/webchange/editor/form_elements/wavesurfer/wavesurfer.cljs
src/cljs/webchange/editor/index.cljs
src/cljs/webchange/editor_v2/views_scene.cljs

- game voice
- book and lion voices
- mari voice (lvl1)
- vera voice (lvl1)

Update game voice for lvl1

---

resources/courses/test/scenes/sandbox.edn
src/cljs/webchange/interpreter/components.cljs
src/cljs/webchange/interpreter/variables/events.cljs

- fix execute-test-var-list
- add a unique key for boxes on sandbox activity
- fix screen ratio for different view boxes

Fix test list action for sandbox activity

---

project.clj
resources/sass/editor-v2.scss
src/clj/webchange/assets/handler.clj
src/clj/webchange/handler.clj
src/cljs/webchange/editor/components/data_sets/common.cljs
src/cljs/webchange/editor_v2/concepts/events.cljs
src/cljs/webchange/editor_v2/concepts/fields.cljs
src/cljs/webchange/editor_v2/concepts/subs.cljs
src/cljs/webchange/editor_v2/concepts/views.cljs
src/cljs/webchange/editor_v2/translator/translator_form/views_form_audio_upload.cljs
src/cljs/webchange/editor_v2/views.cljs
src/cljs/webchange/editor_v2/views_data.cljs
src/cljs/webchange/routes.cljs
src/cljs/webchange/views.cljs

- a new page with course info (concepts, scenes, lessons)
- add/edit form for concept 
only text, audio, image, video types are supported (we want to edit actions in scene translations)
assets uploading form is reused from audio uploading.

Add edit concepts page

---

src/cljs/webchange/editor/events.cljs
src/cljs/webchange/editor_v2/translator/translator_form/utils.cljs
src/cljs/webchange/editor_v2/translator/translator_form/views_form_audios.cljs
test/cljs/webchange/editor_v2/translator/translator_form/utils_test.cljs

Show alias if it is available
Sort audio files by date added.

Sort audio files by date

---

resources/courses/english/scenes/home.edn
resources/datasets/english-concepts.edn
src/cljs/webchange/editor_v2/diagram/modes/phrases/widget_data.cljs
src/cljs/webchange/editor_v2/diagram/modes/translation/widget_data.cljs
src/cljs/webchange/editor_v2/translator/translator_form/utils.cljs
src/cljs/webchange/editor_v2/translator/translator_form/views_form.cljs
src/cljs/webchange/editor_v2/translator/translator_form/views_form_phrase.cljs
test/cljs/webchange/editor_v2/translator/translator_form/utils_test.cljs

- Possibility to concatenate dialog text from action's texts
- Show phrase text on diagram block
- Show dialog description on diagram block

Remake dialog text

---

src/cljs/webchange/editor/form_elements/wavesurfer/wave_core.cljs
src/cljs/webchange/editor_v2/translator/events.cljs
src/cljs/webchange/editor_v2/translator/subs.cljs
src/cljs/webchange/editor_v2/translator/translator_form/views_form.cljs
src/cljs/webchange/editor_v2/translator/translator_form/views_form_audios.cljs
src/cljs/webchange/editor_v2/translator/translator_form/views_form_play_phrase.cljs
src/cljs/webchange/editor_v2/translator/views_modal.cljs

- move data-store and current-concept from atoms to db

Fix select audio block

---

resources/courses/test/scenes/pinata.edn
resources/courses/test/scenes/see_saw.edn
resources/courses/test/scenes/slide.edn
resources/courses/test/scenes/swings.edn
resources/courses/test/scenes/volleyball.edn
src/cljs/webchange/common/anim.cljs
src/cljs/webchange/interpreter/core.cljs
src/cljs/webchange/interpreter/events.cljs

- fix set slots for animation
- fix animation-sequence
- fix Spanish activities

Fix set slots action for animations

---

src/cljs/webchange/student_dashboard/history/views_history_list_item.cljs

Add level and lesson instead of date to history item

Label history items

---

resources/courses/spanish/scenes/cinema.edn
resources/courses/test/scenes/cinema.edn
src/cljs/webchange/interpreter/variables/events.cljs

- allow using default :concepts-all lesson set

Fix cinema activity

---

resources/courses/spanish/scenes/see_saw.edn
resources/courses/spanish/scenes/swings.edn
src/cljs/webchange/interpreter/components/button.cljs
src/cljs/webchange/interpreter/events.cljs
src/cljs/webchange/interpreter/screens/activity_finished.cljs

- fix button on activity finished screen
- show activity finished screen for each finished activity (not only 'next')
- fix see-saw and swings activities

Fix finish activity screen

---

resources/datasets/spanish-concepts.edn
src/cljs/webchange/editor_v2/diagram/widget/views.cljs
src/cljs/webchange/editor_v2/graph_builder/scene_parser/concepts_replacer/replacer.cljs
src/cljs/webchange/editor_v2/graph_builder/utils/node_siblings.cljs
src/cljs/webchange/editor_v2/graph_builder/utils/remove_sub_graph.cljs
test/cljs/webchange/editor_v2/graph_builder/utils/node_siblings_test.cljs

- fix original text for park poem
- fix removing extra nodes (when one node appears two times)
- fix rebuilding graph when the node name is changed.

Fix park poem translation

---

src/cljs/webchange/common/anim.cljs
src/cljs/webchange/common/events.cljs
src/cljs/webchange/core.cljs
src/cljs/webchange/interpreter/events.cljs
src/cljs/webchange/interpreter/variables/core.cljs
src/cljs/webchange/interpreter/variables/events.cljs
test/cljs/webchange/interpreter/variables/events_test.cljs

- slow down animation when frame rate is less than 15.
- store flows, timers, and variables in atoms instead of app-db
- use direct calls instead of events for flow control.

Feature animations optimizations

---

resources/migrations/20200923180214-add-single-background-asset-type.down.sql
resources/migrations/20200923180214-add-single-background-asset-type.up.sql
src/clj/webchange/course/core.clj
src/clj/webchange/course/handler.clj
src/clj/webchange/handler.clj
src/clj/webchange/templates/library/book.clj
src/cljs/webchange/editor_v2/scene/data/stage/views.cljs
src/cljs/webchange/editor_v2/scene/state/background.cljs
src/cljs/webchange/editor_v2/scene/state/stage.cljs
src/cljs/webchange/editor_v2/scene/views_canvas.cljs
src/cljs/webchange/editor_v2/scene/views_data.cljs
src/cljs/webchange/editor_v2/wizard/state/activity.cljs
src/cljs/webchange/editor_v2/wizard/views.cljs
src/cljs/webchange/interpreter/components.cljs
src/cljs/webchange/interpreter/renderer/scene/components/editor_mode.cljs
src/cljs/webchange/routes.cljs
src/cljs/webchange/views.cljs

- add game-changer page
- add "stages" to the editor, so that we can show or hide different objects 
- add single-background type for assets.

Add game changer page

---

src/cljs/webchange/interpreter/renderer/scene/app.cljs
src/cljs/webchange/resources/scene_parser.cljs

Remove all tickers when app reset

Fix cycling back-out

---

project.clj
resources/sql/queries.sql
src/clj/webchange/migrations/kitkit/book_horizontal.clj
src/clj/webchange/migrations/kitkit/book_import.clj
src/clj/webchange/migrations/kitkit/book_vertical.clj
src/clj/webchange/migrations/kitkit/book_vertical_page.clj
src/clj/webchange/migrations/kitkit/loader.clj
src/clj/webchange/server.clj

lein run load-book "/home/pavel/Downloads/mainapp_en_us/Resources/localized/en-us/games/books/bookdata/" 1 en_g
First argument is directory where books is located.
Second is owner id 
Third one is optional. It is directory name to import. If it is not set all books will be imported from given directory.
https://github.com/XPRIZE/GLEXP-Team-KitkitSchool/releases/download/v1.0/library_en_us.tar.gz

KitKit books import

---

src/clj/webchange/course/core.clj
src/clj/webchange/migrations/kitkit/book_horizontal.clj
src/clj/webchange/migrations/kitkit/book_import.clj
src/clj/webchange/migrations/kitkit/book_vertical_page.clj
src/clj/webchange/migrations/onebillion/book_horizontal.clj
src/clj/webchange/migrations/onebillion/book_import.clj
src/clj/webchange/migrations/onebillion/loader.clj
src/clj/webchange/server.clj

lein run load-onebillion-book /home/pavel/Downloads/assets/oc-reading/books/ 1  xr-redraincoat
First argument is directory where books is located.
Second is owner id
Third one is optional. It is directory name to import. If it is not set all books will be imported from given directory.
https://github.com/XPRIZE/GLEXP-Team-onebillion/releases/download/v3.0.1/onecourse-assets-v3.0.1.tar.gz.ab
https://github.com/XPRIZE/GLEXP-Team-onebillion/releases/download/v3.0.1/onecourse-assets-v3.0.1.tar.gz.aa
cat *.tar.gz.* | zcat | tar xvf -

Onebillion books import

---

src/clj/webchange/migrations/kitkit/book_import.clj
src/clj/webchange/templates/library/casa.clj
src/cljs/webchange/editor_v2/diagram_utils/modes/phrases/widget_data.cljs
src/cljs/webchange/editor_v2/scene_diagram/nodes_factory/nodes_factory.cljs
src/cljs/webchange/editor_v2/scene_diagram/scene_parser/actions_tracks.cljs
src/cljs/webchange/editor_v2/scene_diagram/scene_parser/scene_parser.cljs
test/cljs/webchange/editor_v2/scene_diagram/scene_parser/scene_parser_test.cljs

Diagram tracks

---

resources/migrations/20201120152041-collaborators.down.sql
resources/migrations/20201120152041-collaborators.up.sql
resources/sql/queries.sql
src/clj/webchange/auth/handler.clj
src/clj/webchange/auth/website.clj
src/clj/webchange/common/audio_parser/converter.clj
src/clj/webchange/course/core.clj
src/clj/webchange/course/handler.clj
src/clj/webchange/handler.clj
src/cljs/webchange/editor_v2/course_dashboard/views.cljs
src/cljs/webchange/editor_v2/layout/breadcrumbs.cljs
src/cljs/webchange/editor_v2/layout/logo/views.cljs
src/cljs/webchange/editor_v2/layout/toolbar/avatar.cljs
src/cljs/webchange/editor_v2/layout/toolbar/views.cljs
src/cljs/webchange/editor_v2/views.cljs
src/cljs/webchange/editor_v2/wizard/views_game_changer.cljs
src/cljs/webchange/editor_v2/wizard/views_wizard.cljs
src/cljs/webchange/routes.cljs
test/clj/webchange/test/course/handler.clj
test/clj/webchange/test/fixtures/core.clj
test/clj/webchange/test/handler.clj

- add collaborators table
- restrict edit access to course owner or collaborator.
- redirect to website for login
- add links to website user profile and courses list.

Feature website links

---

src/clj/webchange/templates/library.clj
src/clj/webchange/templates/library/categorize/round_1.clj
src/clj/webchange/templates/library/categorize/round_2.clj
src/clj/webchange/templates/library/categorize/round_3.clj
src/clj/webchange/templates/library/categorize_antonims/round_1.clj
src/clj/webchange/templates/library/categorize_antonims/round_2.clj
src/clj/webchange/templates/library/categorize_antonims/round_3.clj
src/clj/webchange/templates/library/categorize_antonims/template.clj
src/clj/webchange/templates/library/categorize_shapes/round_1.clj
src/clj/webchange/templates/library/categorize_shapes/round_2.clj
src/clj/webchange/templates/library/categorize_shapes/round_3.clj
src/clj/webchange/templates/library/categorize_shapes/template.clj
src/clj/webchange/templates/library/categorize_synonyms/round_1.clj
src/clj/webchange/templates/library/categorize_synonyms/round_2.clj
src/clj/webchange/templates/library/categorize_synonyms/round_3.clj
src/clj/webchange/templates/library/categorize_synonyms/template.clj
src/clj/webchange/templates/utils/merge.clj
src/cljs/webchange/interpreter/events.cljs

background.png
circle.png
circle-box.png
circle-table.png
oval.png
oval-box.png
question.png
rectangle.png
rectangle-box.png
square.png
square-box.png
square-table.png
star.png
star-box.png
triangle.png
triangle-box.png
triangle-table.png
This pictures may should be more then one according to document
circles
squares
rectangles
ovals
stars
triangles
back.png
background.png
day.png
down.png
front.png
in.png
left.png
loud.png
night.png
out.png
question.png
quiet.png
right.png
up.png
This pictures may should be more then one according to document
left pictures
back pictures
up pictures
night pictures
out pictures
loud pictures
afraid.png
background.png
big.png
child.png
chilly.png
cold.png
garbage.png
glad.png
happy.png
kid.png
large.png
question.png
scared.png
trash.png
This pictures may …

Categorize templates improvement

---

.gitignore
.run/REPLs.run.xml
.run/backend.run.xml
.run/figwheel.run.xml
env/dev/clj/webchange/dev_templates.clj
env/dev/clj/webchange/dev_templates/interactive_read_aloud.clj
env/dev/repl.clj
env/dev/user.clj
project.clj
src/clj/webchange/course/core.clj
src/clj/webchange/course/handler.clj
src/clj/webchange/migrations/kitkit/book_import.clj
src/clj/webchange/migrations/onebillion/book_import.clj
src/clj/webchange/templates/core.clj
src/clj/webchange/templates/library/flipbook/template.clj
src/clj/webchange/templates/library/interactive_read_aloud.clj
src/cljs/webchange/common/events.cljs

- IntelliJ IDEA REPL build configurations
- Update activities from template dev scripts.

Update activities from template

---

src/cljs/webchange/editor_v2/dialog/dialog_text_form/side_menu/styles.scss

Fixed the menu UI

---

src/cljs/webchange/editor_v2/wizard/activity_template/question/views_preview.cljs
src/cljs/webchange/interpreter/components.cljs
src/cljs/webchange/interpreter/renderer/scene/app.cljs
src/cljs/webchange/interpreter/renderer/stage.cljs
src/cljs/webchange/interpreter/renderer/state/overlays.cljs
src/cljs/webchange/resources/manager.cljs

Reverts VisionsGlobalEmpowerment/webchange#642

Revert "Fix resources loading"

---

src/cljs/webchange/editor_v2/activity_dialogs/form/action_unit/styles.scss
src/cljs/webchange/editor_v2/activity_dialogs/form/state.cljs
src/cljs/webchange/editor_v2/activity_dialogs/form/styles.scss
src/cljs/webchange/editor_v2/activity_dialogs/form/views.cljs
src/cljs/webchange/editor_v2/activity_dialogs/styles.scss

Activity dialogs form

---

src/cljs/webchange/ui_framework/layout/navigation/styles.scss
src/cljs/webchange/ui_framework/layout/navigation/views.cljs

fixed the navigation menu

---

src/cljs/webchange/dashboard/courses/views.cljs

added the confirmation modal

---

src/cljs/webchange/interpreter/components.cljs
src/cljs/webchange/interpreter/renderer/loader_screen.cljs
src/cljs/webchange/interpreter/renderer/stage.cljs

Reverts VisionsGlobalEmpowerment/webchange#772
Book creator is not working properly

Revert "Start activity optimization"

---

src/clj/webchange/templates/library/running.clj
src/clj/webchange/templates/library/running_time_limited.clj
src/cljs/webchange/editor_v2/activity_dialogs/form/action_unit/views_menu.cljs
src/cljs/webchange/editor_v2/activity_dialogs/form/state.cljs
src/cljs/webchange/editor_v2/activity_dialogs/form/state_actions.cljs
src/cljs/webchange/editor_v2/dialog/dialog_form/diagram/items_factory/nodes_factory.cljs
src/cljs/webchange/editor_v2/dialog/dialog_form/state/actions.cljs
src/cljs/webchange/editor_v2/dialog/dialog_form/views_form_diagram.cljs
src/cljs/webchange/editor_v2/layout/components/sandbox/state.cljs

Fix concept phrase adding

---

src/cljs/webchange/editor_v2/activity_dialogs/form/action_unit/views.cljs
src/cljs/webchange/editor_v2/activity_dialogs/form/state.cljs

Work in progress. It's a little slow but we can move action units around, including to and from parallel groups.

Moving action units

---

src/cljs/webchange/editor_v2/activity_dialogs/form/action_unit/styles.scss
src/cljs/webchange/editor_v2/activity_dialogs/form/action_unit/views_common.cljs
src/cljs/webchange/editor_v2/activity_dialogs/form/action_unit/views_text_animation.cljs
src/cljs/webchange/editor_v2/activity_dialogs/form/state.cljs
src/cljs/webchange/ui_framework/components/menu/index.cljs

Fix dialogs form appearance

---

src/cljs/webchange/editor_v2/layout/components/interpreter_stage/views.cljs
src/cljs/webchange/interpreter/components.cljs
src/cljs/webchange/interpreter/renderer/loader_screen.cljs
src/cljs/webchange/interpreter/renderer/stage.cljs

Reverts VisionsGlobalEmpowerment/webchange#776

Revert "Fix start activity"

---

src/clj/webchange/templates/library/onset_and_rime.clj
src/cljs/webchange/interpreter/renderer/scene/filters/filters.cljs

Change pulsation color

---

src/cljs/webchange/book_library/components/button/styles.scss
src/cljs/webchange/book_library/components/button/views.cljs
src/cljs/webchange/book_library/layout/side_menu/styles.scss
src/cljs/webchange/book_library/layout/side_menu/views.cljs
src/cljs/webchange/book_library/mixins.scss
src/cljs/webchange/book_library/pages/read/state.cljs
src/cljs/webchange/book_library/pages/read/styles.scss
src/cljs/webchange/book_library/pages/read/views.cljs
src/cljs/webchange/book_library/styles.scss

Book library updates

---

src/cljs/webchange/book_library/pages/read/styles.scss
src/cljs/webchange/parent_dashboard/styles.scss
src/cljs/webchange/student_dashboard/timeline/play_button/styles.scss
src/cljs/webchange/student_dashboard/timeline/styles.scss
src/cljs/webchange/ui_framework/components/icon_button/styles.scss
src/cljs/webchange/ui_framework/components/select_image/styles.scss
src/cljs/webchange/ui_framework/components/timeline/styles.scss

Reverts VisionsGlobalEmpowerment/webchange#897

Revert "Migrate code"

---

project.clj
resources/public/index.html
resources/public/student.html
src/cljs/webchange/interpreter/events.cljs
src/cljs/webchange/interpreter/renderer/state/scene.cljs

Reverts VisionsGlobalEmpowerment/webchange#902

Revert "Performance updates"
